# Copy this file to secrets.yaml (same folder) and **never** commit it.
# ── Bin an ce API (spot only permissions – no withdrawals!) ─────────────
binance:
  api_key: "PASTE_YOUR_BINANCE_SPOT_API_KEY"
  api_secret: "PASTE_YOUR_BINANCE_SPOT_SECRET_KEY"

# ── Optional notifier credentials (Telegram / Email) ────────────────────
telegram:
  bot_token: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
  chat_id: "987654321"

email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  username: "your@email"
  password: "your_app_password"
  send_to: "you@example.com"
